#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-gradle-groovy-all
Version  : 1
Release  : 1
URL      : https://repo.gradle.org/gradle/libs-releases/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4-sources.jar
Source0  : https://repo.gradle.org/gradle/libs-releases/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4-sources.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-gradle-groovy-all-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-gradle-groovy-all package.
Group: Data

%description data
data components for the mvn-gradle-groovy-all package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4-sources.jar
/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4.jar
/usr/share/java/.m2/repository/org/gradle/groovy/groovy-all/1.3-2.5.4/groovy-all-1.3-2.5.4.pom
